name: BIOMI-RPI

on:
  push:
    branches:
      #- 'main'
      - '**'
env:
  IMAGE_NAME: ghcr.io/prismprotocolhub/biomi-rpi

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free up disk space on GitHub runner
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Docker image
        id: cache
        uses: actions/cache@v4
        with:
          path: /tmp/image.tar
          key: ${{ hashFiles('Dockerfile') }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ${{ env.IMAGE_NAME }}:latest \
            -o type=docker,dest=- \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max \
            . > /tmp/image.tar

  test:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      publish: ${{ steps.check.outputs.publish }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Docker image
        uses: actions/cache@v4
        with:
          path: /tmp/image.tar
          key: ${{ hashFiles('Dockerfile') }}

      - name: Load Docker image
        run: docker load -i /tmp/image.tar

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          pip3 install docker
        env:
          PIP_BREAK_SYSTEM_PACKAGES: 1

      - name: Run tests
        run: |
          ansible-playbook \
            -i test/hosts.yml \
            test/main.yml

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: config
          path: dist

      - name: Check for Tag
        id: check
        run: |
          git fetch --tags
          if [[ ! -z "$(git tag --contains HEAD)" ]]; then
            echo "publish=true" >> $GITHUB_OUTPUT
          fi

  publish:
    if: needs.test.outputs.publish == 'true'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set tag variable
        run: |
          git fetch --tags
          echo "TAG=$(git tag --contains HEAD)" >> $GITHUB_ENV

      - name: Cache Docker image
        uses: actions/cache@v4
        with:
          path: /tmp/image.tar
          key: ${{ hashFiles('Dockerfile') }}

      - name: Load Docker image
        run: docker load -i /tmp/image.tar

      - name: Tag Docker image
        run: docker tag ${{ env.BASE_IMAGE_NAME }}:latest ${{ env.BASE_IMAGE_NAME }}:${{ env.TAG }}

      - name: Tag Docker image
        run: docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Container Registry
        run: docker push ${{ env.BASE_IMAGE_NAME }}:${{ env.TAG }}
          
      - name: Push to GitHub Container Registry
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.TAG }}
